In [1]:
import pandas as pd
from legislator_analyser import LegislatorAnalyser

In [2]:
bills_df = pd.read_csv('input/bills.csv')
legislators_df = pd.read_csv('input/legislators.csv')
votes_df = pd.read_csv('input/votes.csv')
vote_results_df = pd.read_csv('input/vote_results.csv')

In [3]:
vote_results_df.head()

         id  legislator_id  vote_id  vote_type
0  92516784         400440  3321166          2
1  92516770          17941  3321166          2
2  92516768         400414  3321166          2
3  92516753         400380  3321166          2
4  92516734         412393  3321166          2

In [4]:
legislator_analyser = LegislatorAnalyser(legislators_df, vote_results_df)

In [5]:
legislator_analyser.parse_legislators_id_column_to_match_vote_results()

In [6]:
legislator_analyser

In [7]:
#bills_analyser.group_vote_results(['legislator_id', 'vote_type'])
legislator_analyser.split_votes_count_by_vote_type()

In [8]:
legislator_analyser.get_legislators_name()

In [9]:
legislator_analyser.write_csv_by_vote_type()

In [10]:
legislator_analyser.vote_results_df.merge(legislator_analyser.legislators_df, on='legislator_id', how='left')

,legislator_id,num_supported_bills,num_opposed_bills,name_x,name_y
0,15318,1,1,Rep. Andrew Garbarino (R-NY-2),Rep. Andrew Garbarino (R-NY-2)
1,15367,1,1,Rep. Nicole Malliotakis (R-NY-11),Rep. Nicole Malliotakis (R-NY-11)
2,17941,1,1,Rep. Jeff Van Drew (R-NJ-2),Rep. Jeff Van Drew (R-NJ-2)
3,400380,1,1,Rep. Chris Smith (R-NJ-4),Rep. Chris Smith (R-NJ-4)
4,400414,1,1,Rep. Fred Upton (R-MI-6),Rep. Fred Upton (R-MI-6)
5,400440,1,1,Rep. Don Young (R-AK-1),Rep. Don Young (R-AK-1)
6,412393,1,1,Rep. Tom Reed (R-NY-23),Rep. Tom Reed (R-NY-23)
7,412421,1,1,Rep. Adam Kinzinger (R-IL-16),Rep. Adam Kinzinger (R-IL-16)
8,412487,1,1,Rep. David McKinley (R-WV-1),Rep. David McKinley (R-WV-1)
9,412649,1,1,Rep. John Katko (R-NY-24),Rep. John Katko (R-NY-24)
10,904789,1,1,Rep. Don Bacon (R-NE-2),Rep. Don Bacon (R-NE-2)
11,904796,1,1,Rep. Brian Fitzpatrick (R-PA-1),Rep. Brian Fitzpatrick (R-PA-1)
12,905216,1,1,Rep. Ilhan Omar (D-MN-5),Rep. Ilhan Omar (D-MN-5)
13,1269767,1,1,Rep. Alexandria Ocasio-Cortez (D-NY-14),Rep. Alexandria Ocasio-Cortez (D-NY-14)
14,1269775,1,1,Rep. Anthony Gonzalez (R-OH-16),Rep. Anthony Gonzalez (R-OH-16)
15,1269778,1,1,Rep. Ayanna Pressley (D-MA-7),Rep. Ayanna Pressley (D-MA-7)
16,1269790,1,1,Rep. Rashida Tlaib (D-MI-13),Rep. Rashida Tlaib (D-MI-13)
17,1603850,1,1,Rep. Jamaal Bowman (D-NY-16),Rep. Jamaal Bowman (D-NY-16)
18,1852382,1,1,Rep. Cori Bush (D-MO-1),Rep. Cori Bush (D-MO-1)